### ISSUE TITLE
animal - RFID

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#15]
La Valeur par défaut de la liste déroulante est la valeur à la dernière capture si capture = 'non' et rien si capture = 'oui'. 
Si l'on rentre un RFID avec un cap_id non null alors les informations de l'animal pour la dernière capture de l'animal concerné doivent s'afficher en bleu (cf 1.10 cahier des charges).

**Comment by Liinwe** [comment]
Ancien RFID s'affiche en bleu
