### ISSUE TITLE
animal - capture_identifié

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#20]
quand capture est oui, identifié est non par défaut.
quand capture est non, identifié est oui par défaut.
Si l'utilisateur permute identifié sur non, cela veut dire que l'animal a perdu ces identifiant. Dans ce cas il faut une entre dans public.t_correspondance_animal_cor, cor_ancien et cor_valide prendrons la valeur entrée dans le champ N° Animal.
Explications __Cette double entrée avec le même numéro dans cette table nous permet de savoir que l'on doit rechercher la véritable identité de cet anima à l'aide de _la_ génétique__

**Comment by Liinwe** [comment]
Done
