### ISSUE TITLE
Animal - tag og et tag od

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#26]
1- lorsqu'on saisie un tag oreille gauche ou oreille droite, vérifier que l'étiquette n'a pas été posée sur l'oreille gauche ou droite d'un autre animal. 

2- En dessous des cases Tag Oreille Gauche et Tag Oreille Droite ajouter une case à cocher (par défaut elle est décochées) avec le label tag métallique. Si il est cochée le cap_tag_droit_metal et/ou cap_tag_gauche_metal de la table t_capture_cap prennent la valeur TRUE il sont par défaut False.

**Comment by Liinwe** [comment]
Done
