### ISSUE TITLE
blessures - localisation et gravité

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#29]
la localisation influence la gravité (choix en cascade) comme pour les prélèvements

**Comment by Liinwe** [comment]
Done

**Comment by yannickkk** [comment]
Super Bravo. Cependant ....
Un animal peut avoir plusieurs blessures à des endroits différentes. Donc une fois qu'un a créé une blessure et qu'on la traite on a un petit bouton validé. Quand on clique sur celui ci on l'ajoute à un tableau HTML qui s'affiche en dessous de la zone de saisie des blessure. On en rentre une deuxième, une troisième et là zut on s'aperçoit qu'on c'est trompé à la première. Alors on sélectionne la première dans le tableau et on appui sur le bouton supprimer que tu n'as pas oublié de créer à cette effet et là pouf l'enregistrement concerné disparaît devant le public émerveillé. lorsque les blessures sont entrées elle vont dans une colonne unique dans la bdd (voir le cahier des charges). Il fait donc concatener les différentes blessures chaine de caractère unique pour les stocker et les séparer par un ~ pour les séparer. Il est possible que la bdd couine lorsque tu essayes d'enregistrer car le champ en question est probablment limité en nombre de caractère. Si tel est le cas dis le moi on fera évoluer la bdd.

**Comment by Liinwe** [comment]
Fait
(comme c'est une dataTable, on peut accéder à chacune des valeurs indépendamment des autres)

**Comment by yannickkk** [comment]
Bravo c'est vraiment super. Juste une chose
quand tu as deux prélèvements exemple:
![image](https://user-images.githubusercontent.com/39738426/41376588-ef61dd82-6f59-11e8-8857-7f535d772ec4.png)
là ce que je voudrais avoir c'est "localisation1-gravité1-traitement2~localisation2-gravité2-traitement2". le tylpe sépare les deux séquences pas chaque élément de traitement comme tu l'as fait. Si tu peux ajouter un tiret du 6 entre chaque partie (localisation-gravité-traitement c'est encore plus clair. c'est parce que tout cela rentre dans un seul champ dans la bdd. Lors que les gens voudront l'analyser il leur suffira de faire un strsplit avec R et ils auront directement une liste dont chaque élément sera une blessure. tu vois  ?

**Comment by Liinwe** [comment]
C'est fait, 

J'ai mis un inputText en dessous de la DataTable, mais c'est juste pour que tu vois ce que ça donne, mais je l’enlèverai après vu que c'est pas vraiment nécessaire de visualiser ça sur le formulaire

**Comment by yannickkk** [comment]
ou c'est exactement ça tu peux enlever les espaces par contre.
