### ISSUE TITLE
Prelevements

### ISSUE THREAD

**Issue by Liinwe** [yannickkk/electronic_data_sheet#30]
- Fonctionne mais est codé en dur
- Prends énormément de temps pour s'afficher

**Comment by yannickkk** [comment]
Ola,

Je viens de tester ça marche, je ne comprends pas ta deuxième remarque chez moi c'est instantané.

reste à el mettre en musique avec la bd mais le principe est celui là (j'ai pas regardé ton code)

**Comment by Liinwe** [comment]
Le soucis avec le base de données, c'est que on a pas le même nombre de lignes entre localisation, type, contenant et solvant. Et du coup il refuse de construire un dataframe.
Dans l'exemple que tu m'as donné, il y avait le même nombre de colonnes à chaque fois.

Et le code dans l'exemple, créé un dataframe avec pour colonne chacune des conditions (localisation, type, etc....). Mais quand il n'y a pas le même nombre de lignes pour chaque colonne, il se retrouve avec des cases vides.

Du coup je cherche comment faire.

![tableau](https://user-images.githubusercontent.com/39345187/41350141-657c1638-6f12-11e8-9ace-dbc3c149a372.png)

![tables_colonnes](https://user-images.githubusercontent.com/39345187/41350140-655e2d3a-6f12-11e8-89bf-4f1d2ad4ca1f.png)


.

**Comment by Liinwe** [comment]
en fait jcrois que j'ai trouvé !

**Comment by Liinwe** [comment]
J'ai des soucis de nombre de lignes avec la base de données, lors de la création du dataframe.

Mais je pense avoir trouvé le soucis, en fait il manque l'info du solvant pour le mucus dans la table solvant.
Je pense qu'il faudrait rajouter une ligne dans la table solvant : 
*sas_sat_id = 5*  et   *sas_sac_id = 9*  et  *sas_solvant = sac*

![tables_colonnes](https://user-images.githubusercontent.com/39345187/41352860-de24ab2e-6f1a-11e8-8bc3-aef70fa1a648.png)

**Comment by yannickkk** [comment]
Je regarde de suite

**Comment by yannickkk** [comment]
ok tu avais raison c'est rajouté sorry for that sas_sat_id = 5 et sas_sac_id = 9 et sas_solvant = sec

**Comment by Liinwe** [comment]
J'ai réussi à faire la cascade à partir de la base de données, mais pas pour les solvants, je n'arrive pas à trouver la requête me permettant d'avoir le même nombre de lignes que les autres tables. 

A continuer

**Comment by yannickkk** [comment]
allez allez

**Comment by Liinwe** [comment]
Ok je crois que j'ai compris le problème !

Y'a un souci dans la table solvant : 
Il manque une ligne, correspondant à la condition : poils dans un eppendorf ( sat_id = 1 et sac_id = 2 )
Et les lignes sas_id = 6 et sas_id = 7 sont pas bonnes, dans les deux cas, le sas_sac_id associé devrait être : 

- **sas_sac_id = 8** au lieu de 2 , pour les conditions sas_id = 6 et sas_sat_id=6
- **sas_sac_id = 7** au lieu de 2, pour les conditions sas_id = 7 et sas_sat_id=4

![table_solvant](https://user-images.githubusercontent.com/39345187/41479412-5b838eda-70cb-11e8-9fed-2cf8002ae21c.png)
