### ISSUE TITLE
historique - Oulala que c'est vilain

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#31]
J'ai eu le temps de regarder cela ce matin. La requête est fausse, je t'avais demandé de faire apparaitre les senseurs embarqués sur les colliers. Tu as rajouté une table (public.t_equipement_conf_eqc) contenant les identifiants des capteurs mais sans faire le lien avec le reste de la requête. Quand tu fais cela la bdd te fait correspondre chaque enregistrement de  public.t_equipement_conf_eqc avec chaque enregistrement du reste de la requête. Comme cette table à 29 enregistrements la requête renvoie 29 fois le nombre d'enregistrement de v_aniposi_gpsgsm .En français la requête renvoie pour chaque position de chaque animal l'ensemble des configurations de colliers entrées dans public.t_equipement_conf_eqc.
C'est pour cela que la requête qui était déjà longue est maintenant très très longue. Je suis en train de faire des tests pour savoir si on peut garder des vues ou si il faut faire des tables pour aller beaucoup plus vite. Pour cela j'ai corrigé la requête mais je propose que tu cherches de ton coté pour apprendre. Les configurations de colliers que j'ai mis dans la table concerne l'année 2018 (et tu n'as pas ces individus dans la table). J'ai donc ajouté un enregistrement, le dernier de public.t_equipement_conf_eqc qui te permet d'afficher dans l'historique pour l'animal F572 et l'année 2015 .... rien comme senseurs. A toi de retrouver ce résultat.

**Comment by Liinwe** [comment]
Je crois que c'est bon, mais comme jsuis pas sûre d'avoir bien compris ces tables là, à vérifier !

**Comment by Liinwe** [comment]
Ah oui mais mnt du coup il affiche que cet individu là et aucun autre, je reprends

**Comment by yannickkk** [comment]
Ok c'est mieux mais c'est faux car tu devrais avoir 4 ligne dans l'historique pour F572 (ceci étant la ligne que tu affiches semble juste):
![image](https://user-images.githubusercontent.com/39738426/41411321-b138920c-6fdc-11e8-8ecc-27456141bb81.png)

**Comment by yannickkk** [comment]
Aide: en fait tu vas trop vite il te faut une liaison entre public.v_aniposi_gpsgsm et public.t_equipement_conf_eqc sauf que dans  public.v_aniposi_gpsgsm y a pas le champ qui t'intéresse non ?
donc il faut.....l'y mettre

**Comment by Liinwe** [comment]
J'avoue que ça me laisse perplexe, je cherche mais je dois manquer quelque chose

**Comment by Liinwe** [comment]
Maintenant ça affiche les 4 mais j'suis toujours pas sûre honnêtement

**Comment by yannickkk** [comment]
Ben t'as raison de pas être sur parce que c'est .... faux. Il ne devrait pas afficher de capteur pour les années avant 2015 puisqu'il n'y a pas de configuration de collier pour les années antérieures à 2018 à par celle de F572 pour 2015. Allez j'arrête de te torturer voici la réponse. J'ai transformé les vues en table en les adaptant à notre question comme ça ce sera beaucoup plus rapide à priori. On casse les tables et on les recrée au démarrage du Rasp donc elles sont toujours à jour et comme la commande que tu envoies est un select sur des tables ça devrait aller très vite. Test avec des vues et avec cette méthode et vois ce qui est le plus rapide. 
P.S: n'efface rien car il est possible qu'on modifie l'affichage en fonction des idées de mes collègues

----à mettre dans global.R
DROP SCHEMA IF EXISTS historique cascade;
CREATE SCHEMA historique;

DROP TABLE IF EXISTS historique.t_ani_gpsgsm;

CREATE TABLE historique.t_ani_gpsgsm AS
 SELECT t_animal_ani.ani_id,
    t_animal_ani.ani_etiq,
    --t_capture_cap.cap_bague,
    t_capture_cap.cap_annee_suivi,
    t_capture_cap.cap_date,
    t_animal_ani.ani_sexe,
    t_capture_cap.cap_age_classe,
    t_capture_cap.cap_poids,
    t_capture_cap.cap_lpa,
    tr_site_capture_sit.sit_nom_court,
    tr_type_equipement_teq.teq_nom_court,
    t_equipement_eqt.eqt_id_usuel,
    t_equipement_eqt.eqt_id,
    tr_sensors_sen.sen_association,
    tr_eqtmarque_mar.mar_libelle,
    tr_eqtmodel_mod.mod_libelle,
    tj_equipement_animal_eqt_ani_eqa.eqa_date_debut,
    tj_equipement_animal_eqt_ani_eqa.eqa_date_fin,
    --t_animal_ani.ani_mortalite,
    --t_animal_ani.ani_date_mort,
    --t_animal_ani.ani_cause_mort,
    --tj_equipement_animal_eqt_ani_eqa.eqa_activite,
    tj_equipement_animal_eqt_ani_eqa.eqa_probleme,
    --tj_equipement_animal_eqt_ani_eqa.eqa_date_fin_text,
    --tj_equipement_animal_eqt_ani_eqa.eqa_date_fin_arrondi,
    --t_animal_ani.ani_date_mort_arrondi,
    --t_animal_ani.ani_date_mort_text,
    --t_animal_ani.ani_poids_mort,
    --t_animal_ani.ani_poids_mort_na,
    --t_animal_ani.ani_remarque,
    --t_animal_ani.ani_mort_x,
    --t_animal_ani.ani_mort_y,
    --t_animal_ani.ani_inconnu,
    t_capture_cap.cap_faon,
    --t_capture_cap.cap_age,
    --t_capture_cap.cap_age_corrige,
    t_capture_cap.cap_circou
    --t_capture_cap.cap_etat_sante,
    --t_capture_cap.cap_heure_lacher,
    --tr_site_capture_sit.sit_id
   FROM t_animal_ani
     LEFT JOIN t_capture_cap ON t_capture_cap.cap_ani_id = t_animal_ani.ani_id
     LEFT JOIN tj_equipement_animal_eqt_ani_eqa ON tj_equipement_animal_eqt_ani_eqa.eqa_ani_id = t_capture_cap.cap_ani_id AND tj_equipement_animal_eqt_ani_eqa.eqa_annee_suivi = t_capture_cap.cap_annee_suivi
     LEFT JOIN t_equipement_eqt ON t_equipement_eqt.eqt_id = tj_equipement_animal_eqt_ani_eqa.eqa_eqt_id
     LEFT JOIN tr_type_equipement_teq ON tr_type_equipement_teq.teq_id = t_equipement_eqt.eqt_teq_id
     LEFT JOIN tr_site_capture_sit ON t_capture_cap.cap_sit_id = tr_site_capture_sit.sit_id
     LEFT JOIN tr_eqtmarque_mar ON t_equipement_eqt.eqt_mar_id = tr_eqtmarque_mar.mar_id
     LEFT JOIN tr_eqtmodel_mod ON t_equipement_eqt.eqt_mod_id = tr_eqtmodel_mod.mod_id
     LEFT JOIN t_equipement_conf_eqc ON t_equipement_eqt.eqt_id = t_equipement_conf_eqc.eqc_eqt_id and t_equipement_conf_eqc.eqc_annee_suivi = t_capture_cap.cap_annee_suivi
     LEFT JOIN lu_tables.tr_sensors_sen ON tr_sensors_sen.sen_id = t_equipement_conf_eqc.eqc_sen_id
  WHERE (tr_type_equipement_teq.teq_id = ANY (ARRAY[2, 3])) AND (t_capture_cap.cap_id IN ( SELECT min(t_capture_cap_1.cap_id) AS min
           FROM t_capture_cap t_capture_cap_1
          GROUP BY t_capture_cap_1.cap_ani_id, t_capture_cap_1.cap_annee_suivi)) AND (tr_type_equipement_teq.teq_id = ANY (ARRAY[2, 3]))
  ORDER BY t_capture_cap.cap_annee_suivi, t_capture_cap.cap_date, t_animal_ani.ani_etiq;

ALTER TABLE historique.t_ani_gpsgsm
  OWNER TO ychaval;
  --GRANT ALL ON TABLE historique.t_ani_gpsgsm TO ychaval;
  --GRANT SELECT ON TABLE historique.t_ani_gpsgsm TO cefs_lecture;
  --GRANT ALL ON TABLE historique.t_ani_gpsgsm TO cefs_ecriture;

COMMENT ON TABLE historique.t_ani_gpsgsm
  IS 'Table contenant toutes les informations des individus équipés de GPS et de GSM (en dehors des locs) - si 2 captures la même année seule la première est conservée';


 DROP TABLE IF EXISTS historique.t_aniposi_gpsgsm;

CREATE TABLE historique.t_aniposi_gpsgsm AS
 SELECT v_posi_gpsgsm.cpos_id,
    --v_ani_gpsgsm.ani_id,
    t_ani_gpsgsm.ani_etiq,
    --v_ani_gpsgsm.cap_bague,
    t_ani_gpsgsm.cap_annee_suivi,
    t_ani_gpsgsm.cap_date,
    t_ani_gpsgsm.ani_sexe,
    t_ani_gpsgsm.cap_age_classe,
    t_ani_gpsgsm.cap_poids,
    t_ani_gpsgsm.cap_lpa,
    t_ani_gpsgsm.sit_nom_court,
    t_ani_gpsgsm.teq_nom_court,
    t_ani_gpsgsm.eqt_id_usuel,
    t_ani_gpsgsm.eqt_id,
    t_ani_gpsgsm.sen_association,
    t_ani_gpsgsm.mar_libelle,
    t_ani_gpsgsm.mod_libelle,
    t_ani_gpsgsm.eqa_date_debut,
    t_ani_gpsgsm.eqa_date_fin
    --v_ani_gpsgsm.ani_mortalite,
    --v_ani_gpsgsm.ani_date_mort,
    --v_ani_gpsgsm.ani_cause_mort,
    --v_ani_gpsgsm.eqa_activite,
    --v_ani_gpsgsm.eqa_probleme,
    --v_ani_gpsgsm.eqa_date_fin_text,
    --v_ani_gpsgsm.eqa_date_fin_arrondi,
    --v_ani_gpsgsm.ani_date_mort_arrondi,
    --v_ani_gpsgsm.ani_date_mort_text,
    --v_ani_gpsgsm.ani_poids_mort,
    --v_ani_gpsgsm.ani_poids_mort_na,
    --v_ani_gpsgsm.ani_remarque,
    --v_ani_gpsgsm.ani_mort_x,
    --v_ani_gpsgsm.ani_mort_y,
    --v_ani_gpsgsm.ani_inconnu,
    --v_ani_gpsgsm.cap_faon,
    --v_ani_gpsgsm.cap_age,
    --v_ani_gpsgsm.cap_age_corrige,
    --v_ani_gpsgsm.cap_circou,
    --v_ani_gpsgsm.cap_etat_sante,
    --v_ani_gpsgsm.cap_heure_lacher,
    --v_ani_gpsgsm.sit_id,
    --v_posi_gpsgsm.the_geom,
    --v_posi_gpsgsm.pos_x,
    --v_posi_gpsgsm.pos_y,
    --v_posi_gpsgsm.pos_systeme,
    --v_posi_gpsgsm.pos_z,
    --v_posi_gpsgsm.pos_x_corrige,
    --v_posi_gpsgsm.pos_y_corrige,
    --v_posi_gpsgsm.pos_z_corrige,
    --v_posi_gpsgsm.pos_nb_sat,
    --v_posi_gpsgsm.pos_dop,
    --v_posi_gpsgsm.pos_dop_corrige,
    --v_posi_gpsgsm.pos_fixstatus,
    --v_posi_gpsgsm.pos_validated,
    --v_posi_gpsgsm.cpos_date,
    --v_posi_gpsgsm.cpos_heure,
    --v_posi_gpsgsm.cpos_delta,
    --v_posi_gpsgsm.cpos_prog6heure,
    --v_posi_gpsgsm.cpos_prog4heure,
    --v_posi_gpsgsm.cpos_prog3heure,
    --v_posi_gpsgsm.cpos_prog1heure,
    --v_posi_gpsgsm.cpos_prog10minutes,
    --v_posi_gpsgsm.date_capture,
    --v_posi_gpsgsm.pos_distance_route,
    --v_posi_gpsgsm.pos_distance_bois,
    --v_posi_gpsgsm.pos_distance_bati,
    --v_posi_gpsgsm.pos_distance_haie,
    --v_posi_gpsgsm.pos_localisation_par_id,
    --tr_parcellaire_par.par_os,
    --tr_parcellaire_par.par_grd_cat,
    --tr_parcellaire_par.par_annee
   FROM historique.t_ani_gpsgsm
     JOIN v_posi_gpsgsm ON t_ani_gpsgsm.ani_id = v_posi_gpsgsm.ani_id AND t_ani_gpsgsm.cap_annee_suivi = v_posi_gpsgsm.cpos_annee_suivi
     --LEFT JOIN tr_parcellaire_par ON v_posi_gpsgsm.pos_localisation_par_id = tr_parcellaire_par.par_id AND v_posi_gpsgsm.cpos_annee_suivi =
     -- tr_parcellaire_par.par_annee
  ORDER BY t_ani_gpsgsm.ani_id, v_posi_gpsgsm.cpos_date, v_posi_gpsgsm.cpos_heure
WITH DATA;

ALTER TABLE historique.t_aniposi_gpsgsm
  OWNER TO ychaval;
  --GRANT ALL ON TABLE historique.t_aniposi_gpsgsm TO ychaval;
  --GRANT SELECT ON TABLE historique.t_aniposi_gpsgsm TO cefs_lecture;
  --GRANT ALL ON TABLE historique.t_aniposi_gpsgsm TO cefs_ecriture;

COMMENT ON table historique.t_aniposi_gpsgsm
  IS 'Table contenant toutes les informations des individus équipés de GPS et de GSM y compris les localisations, les distances et l assolement lorsque présent';


----à mettre dans la fonction server en remplacement de la requête précédente en remplaçant F572 par l'input$....
SELECT ani_etiq, count(cpos_id), cap_annee_suivi, cap_date, ani_sexe, cap_age_classe,
       cap_poids, cap_lpa, sit_nom_court, teq_nom_court, eqt_id_usuel,
       eqt_id, sen_association, mar_libelle, mod_libelle, eqa_date_debut,
       eqa_date_fin
  FROM historique.t_aniposi_gpsgsm where ani_etiq = 'F572'
group by ani_etiq, cap_annee_suivi, cap_date, ani_sexe, cap_age_classe,
       cap_poids, cap_lpa, sit_nom_court, teq_nom_court, eqt_id_usuel,
       eqt_id, sen_association, mar_libelle, mod_libelle, eqa_date_debut,
       eqa_date_fin order by cap_annee_suivi

**Comment by Liinwe** [comment]
Ok je teste ça dès demain matin, mais j'suis pas sure de pouvoir vu que j'ai pas de droits d'écriture sur la base !

**Comment by Liinwe** [comment]
![capturee](https://user-images.githubusercontent.com/39345187/41461795-02b11eb0-7091-11e8-9a54-e2f0cc3ab625.PNG)

**Comment by yannickkk** [comment]
tu peux le faire en localhost et remplace OWNER TO ychaval par OWNER TO public.
Si tu arrives à le tester localement on le testera lundi sur le serveur.

**Comment by Liinwe** [comment]
Nope ça ne marche pas, en fait même sur ma copie locale, je n'avais pas pu copier les vues, des problèmes de permissions aussi. Du coup même en local je peux pas, j'pense que le mieux c'est qu'on regarde lundi, je continue le reste en attendant.

![permission](https://user-images.githubusercontent.com/39345187/41472293-474d5eba-70b6-11e8-9500-e67adffc740f.PNG)
