### ISSUE TITLE
Prélèvements - Ajouter tableau listant les prélèvements 

### ISSUE THREAD

**Issue by Liinwe** [yannickkk/electronic_data_sheet#33]
Possibilité d'ajouter et de supprimer un prélèvement

**Comment by Liinwe** [comment]
Fait

**Comment by yannickkk** [comment]
les boutons prennent trop de place il faudrait qu'il soient l'un à coté de l'autre.
d'ailleurs diarrhée et tiques seront également à virer et à mettre avec circou, longuer de patte et tout ça.

**Comment by Liinwe** [comment]
Comme ça ?
![capture](https://user-images.githubusercontent.com/39345187/41383327-82d3c006-6f70-11e8-9a3a-6966442bf7fb.PNG)

**Comment by yannickkk** [comment]
yep
