### ISSUE TITLE
Animal - Rfid

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#34]
Quand première capture = non et identifié = oui si N° Animal n'est pas null et que RFID est null alors il faut bloquer rfid pour que l'utilisateur soit obligé d'utiliser RFID_new

**Comment by Liinwe** [comment]
Fait

**Comment by yannickkk** [comment]
oui quand l'animal n'a pas de RFID, alors RFID disparait pour laisser la place à RFID_new ça c'est nickel
![image](https://user-images.githubusercontent.com/39738426/41416623-9b44fc1a-6feb-11e8-8d8e-dff3f71afc05.png)

mais RFID_new a disparu lorsqu'un animal a déjà un rfid alors qu'il devrait toujours être là. Car l'animal peut avoir déjà un RFID mais l'avoir perdu dans ce cas on en réinjecte un nouveau:

![image](https://user-images.githubusercontent.com/39738426/41416520-5311991c-6feb-11e8-97f3-0254725e7e99.png)

**Comment by Liinwe** [comment]
c'est corrigé
