### ISSUE TITLE
Collier

### ISSUE THREAD

**Issue by Liinwe** [yannickkk/electronic_data_sheet#35]
**Pose d’un collier** : 

- checkboxinput qui permet l'affichage d'un tableau HTML avec le choix possibles des colliers lorsqu'elle est cochée 
- Possibilité de sélectionner qu'une seule ligne du tableau
- Le choix fait devra être validé par un bouton action.
- Lors de la validation, si la case "pose d'un collier" est cochée mais qu’il n’y a pas d’association entre l’animal concerné et un collier, il faut envoyer un pop-up avec :
« Animal équipé d’un collier mais entrée non validée, validez ou décochez la case "pose d’un collier" ? »

**Comment by Liinwe** [comment]
Fait

**Comment by yannickkk** [comment]
Le collier choisi devrait afficher "tec_nom_court": collier "eqc_couleur_collier" boitier "eqc_couleur_boitier"

**Comment by yannickkk** [comment]
pour le reste je pense que c'est bien bravo

**Comment by Liinwe** [comment]
C'est corrigé !

**Comment by yannickkk** [comment]
affiche "GPS-bleu-rouge" ce que j'avais demandé c'est "GPS: collier ROUGE  boitier BLEU"
R toupper(x) pour passer la casse en majuscule.
