### ISSUE TITLE
Table - Température

### ISSUE THREAD

**Issue by Liinwe** [yannickkk/electronic_data_sheet#36]
**2 listes de choix :  "sonde" et "positionnement" :**
- ~~sonde "rouge" : si sonde rouge alors par défaut anus dans *lu_tables.tr_temperatures_loc_tel*~~
- ~~sonde "blanche" : si sonde blanche alors par défaut extérieur dans *lu_tables.tr_temperatures_loc_tel*~~

**Un bouton à cocher "suivi des températures"**
- Lorsqu'il est coché, on rempli la table *public.t_temperatures_tem* avec pour un identifiant de capture *cap_id* (donc un animal), les données prises toutes les secondes pour les deux sondes avec *tem_tel_id* qui prend la valeurs déterminées avec les listes de choix précédentes.

- Lorsque la case "suivi des températures" est décochée ou que l'on relâche l'animal (qu'on va sur la rubrique "comportement au lâché") alors le suivi s'arrête.

**Un tableau html qui affichera** : 
- *l'ani_etiq* de l'animal
-  l'heure du début de suivi des températures, 
- la première valeur de température correspondante, 
- puis sera affiché 1 valeur de température toutes les deux minutes dans le tableau afin d'avoir un suivi durant la manip.

**Comment by yannickkk** [comment]
on regardera cela en détail lundi aussi j'avais dû prendre des notes quand ej l'ai fait

**Comment by Liinwe** [comment]
doublon
