### ISSUE TITLE
Animal - poids

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#45]
J'ai sélectionné le sabot 1, entré des valeurs de 650 kilos dans poids de sabot plein, la pop up a fonctionnée, j'ai annulé puis ressaisi 65 kilos puis 32 kilos dans poids sabot vide. L'app affiche poids animal 33 mais plante et Error: argument is of length zero ....
dans la console:
Listening on http://127.0.0.1:5183
Warning: Error in if: argument is of length zero
Stack trace (innermost first):
    79: renderUI [C:\Users\ychaval\Documents\Collegues\Etudiants\JEREMIE_Marie\Programmes\R\electronic_data_sheet\cahier_electronique/server.R#313]
    78: func
    77: origRenderFunc
    76: output$perte_poids
     1: runApp

raison: quand on rentre le poids, le numéro de l'animal n'est pas toujours connu il faut donc attendre qu'il
le soit pour faire le test du poids.
On peut également supprimer les warnings

**Comment by Liinwe** [comment]
j'ai créé un ticket pour le blocage des warnings
