### ISSUE TITLE
suivi de température

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#57]
le bouton "Suivi des températures" sera placé juste en dessous de sonde et positionnement.
Une fois que ce bouton est coché le suivi commence et lorsqu'il est décoché, le suivi s'arrête.
Un graph est produit en temps réel avec les données collectée par les deux sondes (courbe rouge = sonde rouge, courbe noire = sonde blanche). Lorsque la prise de données est interrompue, le graph d'arrêt et lorsque la collecte reprend le graph reprend.

**Comment by yannickkk** [comment]
pour aller lire la mesure des sondes de température
patch sonde blance 031724cb00ff:
/sys/bus/w1/devices/28-031724cb00ff

patch sonde rouge 0417503f2cff:
/sys/bus/w1/devices/28-0417503f2cff

**Comment by Liinwe** [comment]
C'est fait, si tu veux le tester, il faut que tu changes le chemin des fichiers **w1slave** dans le code ( j'ai laissé le chemin de mon ordi pour le moment pour pouvoir le tester quand j'ai besoin)

**Comment by yannickkk** [comment]
J'ai testé bravo ça marche. Cependant il fait très rarement plus de 20°C quand on fait des captures il faudrait donc deux échelles une pour la courbe bleu et une pour la rouge:
https://www.r-bloggers.com/r-single-plot-with-two-different-y-axes/
D'autre part je suis pas très fan de al mise en page ce serait mieux d'avoir splitlayout avec à gauche les valeurs choisies (et suivi des températures au dessus des deux sondes) et à droite le graphique (tu peux réduire la longueur des abscisses.
