### ISSUE TITLE
Enregistrer les données - Checklist1

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#58]
lorsqu'on presse sur enregistrer les données.
Le premier enregistrement à faire est sous la forme d'un fichier .csv (write.csv) ce fichier est enregistré (1-sur la carte sd du raspberry, 2- sur une clef usb connectée au raspberry, 3- sur la tablette si possible).

**Comment by Liinwe** [comment]
j'ai le début de cette partie qui fonctionne, l'appli plante pour le moment après, mais ça crée quand même le fichier ( avec qques données "animal" pour le moment).

Ca ne marche pas encore pour toutes les conditions, c'est "en travaux " !

**Comment by Liinwe** [comment]
Une question, pour cette partie (cf photo), tu veux que dans chaque case il y ait "oui" ou "non" ou bien un truc du genre "sang-jugulaire-tube rouge-sec-2" ?

![question](https://user-images.githubusercontent.com/39345187/41779612-adac9492-7632-11e8-8932-6e968cc58f81.PNG)

**Comment by yannickkk** [comment]
ça va dans cette table donc comme ça "sang-jugulaire-tube rouge-sec-2". Ainsi sang sera transformé en sat_id, jugulaire en sal_id, tube rouge en sac_id, sec en sas__d et 2 en sca_value
![image](https://user-images.githubusercontent.com/39738426/41780275-92f9aa48-7634-11e8-86a6-379377464877.png)

**Comment by Liinwe** [comment]
Alors, pour tester l'enregistrement sur le .csv : 

Pour le moment il faut remplir normalement les données que tu veux dans les rubriques, puis tu vas dans la checklist 1 et tu cliques sur "enregistrer les données" puis tu valides (peu importe si tout est rempli ou pas).

Et là normalement ça t'a créé un fichier nommé "testest.csv" avec les différentes colonnes remplies. ( Il me manque encore quelques enregistrements de certaines données à programmer.)

Pour le moment, ça "append" les données des différents animaux les uns en dessous des autres.

J'ai aussi réussi à faire en sorte que lorsqu'on enregistre les données vers le .csv, la page s'actualise donc ça vide toutes les données précédentes.

Ps : j'ai rajouté 2 packages sur le global

**Comment by Liinwe** [comment]
Le csv est terminé, pas testable dans sa totalité tant que j'ai pas fait en sorte que la première partie des données soient enregistrée dans la base ( pour pouvoir récupérer le numéro de sabot)
