### ISSUE TITLE
Animal - N° Animal - delay

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#61]
lorsqu'un animal est capturé pour al première fois et que l'on rentre son numéro, si il s'appelle 3012 par exemple on n'a pas le temps de taper le code que déjà la popup attention l'animal existe apparait car 3 existe 30 existe et 301 existe. Il faut donc temporiser l'alerte de façon à ce que l'utilisateur est le temps de rentrer son numéro entier .... 2 ou 3 secondes. 
Même chose pour les tag des oreilles

**Comment by yannickkk** [comment]
cool mais pour les tags oreille lorsque je rentre ça:
![image](https://user-images.githubusercontent.com/39738426/42058886-10e89738-7b22-11e8-91ee-b5045d36b24f.png)
3020 n'existe effectivement mais les tag 191 et 192 existent et rien ne se passe pour m'avertir !!

**Comment by yannickkk** [comment]
je parle d'une capture dans le poste d'avant

**Comment by Liinwe** [comment]
C'est corrigé, ça te va le délai d'apparition du pop-up ?
