### ISSUE TITLE
Animal - Nouveau tag 

### ISSUE THREAD

**Issue by Liinwe** [yannickkk/electronic_data_sheet#84]
Créer : 
- ~~Un champ new tag oreille G~~
- ~~Un champ new tag oreille D~~
- ~~checkbox Tag gauche métal~~ 
- ~~checkbox Tag droit métal~~ 
- ~~Mettre des checkbox "nouveau tag" "nouvel RFID" pour afficher les champs seulement quand nécessaire~~

**Comment by yannickkk** [comment]
??? je vois ou c'est fait ?

**Comment by yannickkk** [comment]
je vois pas ou c'est fait voulais je dire

**Comment by Liinwe** [comment]
j'avais oublié de commit !

**Comment by yannickkk** [comment]
ya un problem quand on sélectionne un individu lors d'une recapture ces tag droite et gauche ne s'affichent plus

**Comment by yannickkk** [comment]
on y est presque quand tu sélectionnes un individu en recapture RFID_new apparait à coté RFID (c'était comme ça avant) et du coup quand tu coche nouveau RFID, RFID se transforme en RFID_new et du coup il y a deux RFID_new fais péter celui qui apparait au début il ne sert plus  rien.
