### ISSUE TITLE
CSV et enregistrement - Animal

### ISSUE THREAD

**Issue by Liinwe** [yannickkk/electronic_data_sheet#85]
Reprendre les sauvegardes avec les nouvelles possibilités de nouveaux TAG OREILLE DROITE et TAG OREILLE GAUCHE (et leurs tag_metal) associés.

**Comment by yannickkk** [comment]
j'essaye de sauver, l'appli plante sans créer de fichier csv, du coup je peux pas faire grand chose. 
Dis moi quand ça ira mieux qu'on essaye de regarder cela

**Comment by Liinwe** [comment]
Ça met quoi comme erreurs dans la console R ?

**Comment by yannickkk** [comment]
difficile de comprendre le comportement de l'appli, un coup ça sauve (capture avec tous les prélèvements) la plupart du temps ça plante (recapture et capture avec des absences de prélèvement), je suis dubitatif car il n'y pas de message d'erreur clair. J'essaierai de détailler tout cela demain

**Comment by Liinwe** [comment]
Ok, mais fais moi des screenshots, j'ai l'habitude mnt des messages R

**Comment by Liinwe** [comment]
Ok, il y avait bien un soucis avec l'enregistrement des prélèvements dans le csv. Normalement c'est résolu
