### ISSUE TITLE
Animal tag metal

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#87]
![image](https://user-images.githubusercontent.com/39738426/42228428-3990c9d8-7ee4-11e8-81ff-256dca228cae.png)

Dans cet exemple les tag métal ne sont pas bon. Déjà on a deux fois t. G.métal alors qu'on devrait avoir aussi t.D.métal. Ensuite il devrait dans cet exemple y avoir la cas cochée pour le tag droit et pas pour le tag gauche. Tu n'es pas la seule responsable car il y avait aussi des erreurs dans al table capture du serveur (elle est corrigée maintenant et el serveur remarche). Cependant avec l'erreur tu devrais avoir l'inverse cad coché pour tag gauche et décoché pour tag droit hors ce n'est pas le cas.

**Comment by Liinwe** [comment]
Les 2 tags métal G, je l'avais corrigé mais pas commit, par contre je vais vérifier si c'est encore inversé ou pas

**Comment by yannickkk** [comment]
Oui je viens d'essayer sur la bdd corrigée et ça à l'air de marcher.
