### ISSUE TITLE
animal - nouvel animal

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#9]
Nouvel Animal (urgence forte)
Pas assez visible passer à des cases oui/non avec oui par défaut.
Pour répondre au 1.6 du cahier des charges (animal recapturé mais sans ses identifiants), je propose de créer un deuxième champ (identifié). Par défaut capture est oui et identifié est non. Si capture est non alors la valeur par défaut d’identifié devient oui. Si l’opérateur clique sur non pour identifié cela veut dire que l’on recapture un animal qui a perdu ses identifiants dans ce cas voir cahier des charges (1.6).
Capture        Identifié

**Comment by Liinwe** [comment]
champ "identifié" crée
Capture "oui" => identifié devient "non"
Capture "non" => identifié devient "oui"
Pop up si le numéro animal entré existe déjà
