### ISSUE TITLE
Animal - "lire rfid"

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#94]
Faire un bouton qui permet de lancer le code que je t'ai envoyé (lect_trans) et de récupérer:
- le code du tag;
- la date;
- l'heure;
et de remettre à l'heure l'horloge du raspberry.

**Comment by Liinwe** [comment]
fait mais à tester

**Comment by Liinwe** [comment]
a tester

**Comment by yannickkk** [comment]
ok ça marche pour le rfid il trouve bien l'individu en question c'est cool par contre ce qeu je voudrais c'est que l'on mettre à l'heure l'horloge du raspberry avec l'heure et la date pas les champs heure set date de la fiche animal (enfin si tu veux mais c'est pas important).
ci-dessous le code de lect_trans avec un transpondeur déjà posé pour que tu puisses vérifier.
@+

library(serial)
library(audio)
# rm(list = ls())
# close(trovan)
# trovan<-serialConnection("get_rfid", port = "COM4", mode ="9600,N,8,1", newline = 1, translation = "cr", handshake = "xonxoff") 
# wait(1)
# open(trovan)
# wait(1)
# inf<- "NA";
# # while (inf != "IOK"){inf<-write.serialConnection(trovan,"I")}
# #wait(1)
# while (inf != "DONE"){inf<-write.serialConnection(trovan,"N")} ######  Dump the contents of all Lots in #reader memory. The ID code is sent with the most significant 2 hexadecimal digits first and the least #significant 2 hexadecimal digits last.
# wait(2.5)
res<-"01000786BB6E18070901110217430000NOK"   ###read.serialConnection(trovan) ####resultat lecture
rfid<-substr(res,3,12) #####tag rfid a lier avec la table animal
lot<-substr(res,1,2)
year<-paste0("20",substr(res,13,14))
month<-substr(res,15,16)
day<-substr(res,17,18)
hour<-as.numeric(substr(res,19,20))+8 ###extraction remise a l'heure
minute<-as.numeric(substr(res,21,22))+3 ###extraction remise a l'heure
second<-substr(res,23,24)
time<-paste0(hour,":",minute,":",second)
date<-paste0(year,"-",month,"-",day)
# while (inf != "DONE"){
# inf<-write.serialConnection(trovan,"C")}######clear memory take between 30 and 40 seconds
# wait(3)
#rm(res)
#close(trovan)

**Comment by yannickkk** [comment]
ha zut il prend les commentaires pour du gras il interprête en markdown, bref tu prends la partie pas en gras du coup

**Comment by yannickkk** [comment]
sudo date -s "Thu Aug  9 21:31:26 UTC 2012" quelque chose comme ça

**Comment by yannickkk** [comment]
ok fait mais à tester sur le Raspberry
