### ISSUE TITLE
table

### ISSUE THREAD

**Issue by yannickkk** [yannickkk/electronic_data_sheet#96]
quand il n'y a pas de temps de fin table, l'App plante, il faut qu'elle ne plante pas même si ce champ n'est pas renseigné

**Comment by Liinwe** [comment]
j'ai push

**Comment by yannickkk** [comment]
Salut t'as fait quoi exactement ça ne marche plus du tout !!

**Comment by yannickkk** [comment]
bon ça à l'air de marcher tout cela cool. J'ai eu pas de soucis de rapidité à l'ouverture de l'application (ouverture en plus de 30 secondes) semble t'il à cause du test de connexion à la bdd distante. J'ai commenté cette partie dans Connect.R
